version: "3.9"

services:
  backend:
    build: ./backend
    container_name: wedding_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/database.db:/app/database.db
    env_file:
      - .env 